name: flutter2
description: Flutter2

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  image_picker: ^0.7.4
  flutter:
    sdk: flutter
  camera:
  date_range_picker: ^1.0.7

  path_provider: ^2.0.1
  js: ^0.6.2
  flutter_spinkit: ^5.0.0
  flutter_feather_icons: ^2.0.0+1
  lite_rolling_switch: ^0.1.1
  responsive_layout_builder: ^0.5.0

  flappy_search_bar: ^1.7.2
  shared_preferences: ^2.0.5
  autocomplete_textfield: ^1.7.3
  provider: ^4.3.2+1
  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  cloud_firestore_web: ^1.0.7
  responsive_builder: ^0.4.1

  firebase_auth: ^1.1.1
  firebase_auth_oauth: ^1.0.1
  firebase_database: ^6.1.2
  firebase_storage: ^8.0.5
  firebase_core: ^1.0.4
  firebase_core_platform_interface: ^4.0.0
  cloud_firestore: ^1.0.6
  cloud_functions: ^1.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_statusbarcolor: ^0.2.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
      - assets/
      - assets/images/
      - assets/icon/
      
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-Italic
      fonts:
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_Medium.ttf
