name: flutter2
description: Flutter2

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  image_picker: ^0.7.4
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  js: ^0.6.2
  shared_preferences: ^2.0.5
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  firebase_core_platform_interface: ^4.0.0
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.0 
  getwidget: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_statusbarcolor: ^0.2.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
      - assets/images/
      - assets/icon/
      
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf